# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Stage 1: Build using Bun
FROM oven/bun:alpine AS builder
WORKDIR /app
# Copy project files
COPY . /app
# Install dependencies and build
RUN bun install
RUN bun run build

# Stage 2: Production image
FROM node:lts-alpine
WORKDIR /app
# Copy package.json to install prod dependencies
COPY package.json /app/
# Install production dependencies
RUN npm install --production
# Copy built files and source if needed
COPY --from=builder /app/dist /app/dist

# Expose nothing (stdio)
# Default command
ENTRYPOINT ["node", "dist/main.js"]
